stages: 
    - build
    - test
    - deploy

.build_project:
    image: python:3.8.10-slim
    stage: build
    script: 
        - pip install -r requirements.txt
        #- apk add curl 
        #- streamlit run heart_disease_app.py       
test:
    image: python:3.8.10-slim
    stage: .pre
    script:
        - pip install pycurl
        - pip install -r requirements.txt
        - streamlit run heart_disease_app.py &
        - sleep 10
        - curl http://localhost:8501 | grep "Heart Disease Diagonistic App"
        


.deploy app:
    stage: deploy 
    image: ruby:latest
    rules:
        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    script:
        - gem install dpl 
        - dpl --provider=heroku --api_key=$HEROKU_API_KEY --app=$HEROKU_APP_NAME

    
        

